### ISSUE TITLE
Installation of 2 ATS on Separate Servers

### ISSUE THREAD

**Issue by marcokonsultex** [aborroy/acs-transform-cluster#1]
Hi Angel,

using this project that you created to use 2 containers with the ATS to improve the balance of document transformations, I ask:

- Is it possible to install 2 ATS on separate servers using Alfresco Community? If so, is there any documentation?

I installed it and saw that it works satisfactorily for our purpose, which is to better manage the transformation of large documents without generating overhead.

Thanks 

Marco Gianini

**Comment by aborroy** [comment]
ATS is not supported for Community, but you can deploy 2 `transform-core-aio` services (as described in this project)

**Comment by marcokonsultex** [comment]
Thanks for the feedback Angel.

As I don't have much experience with docker, is there any documentation that can verify placement of 2 transform-core-aio on different servers?

1 transform-core-aio on server_1 and another transform_Core_aio on server_2.

Sorry if I didn't explain myself correctly.

**Comment by aborroy** [comment]
It's exactly what is described in this sample:
https://github.com/aborroy/acs-transform-cluster/blob/main/acs-community/docker-compose.yml

Define (or install) a Web Proxy:
```
    transform-core-aio-proxy:
        image: nginx:stable-alpine
        depends_on:
            - transform-core-aio-1
            - transform-core-aio-2
```

Define (or install) 2 Transform Core instances:
```
    transform-core-aio-1:
        image: alfresco/alfresco-transform-core-aio:2.5.3

    transform-core-aio-2:
        image: alfresco/alfresco-transform-core-aio:2.5.3
```

Configure Alfresco to use the Proxy as Transformer:

```
-DlocalTransform.core-aio.url=http://transform-core-aio-proxy/
```

Define balancing policy in Web Proxy for your Transformer instances:
https://github.com/aborroy/acs-transform-cluster/blob/main/acs-community/config/nginx-core-aio.conf

>> Having, at least, basic skills to read Docker Compose and Dockerfile files is a must these days
